sudo: false
language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
os:
  - linux
  - osx
compiler:
  - gcc
  - clang
env:
  global:
    - RUST_BACKTRACE=1
    - LLVM_VERSION=3.9
before_script:
  - .travis/before-install.sh
  - cd fasthash
script:
  - cargo test
cache:
  cargo: true
  directories:
    - $HOME/.cargo