sudo: false
language: rust
rust:
  - stable
  - beta
  - nightly
os:
  - osx
  - linux
matrix:
  allow_failures:
    - rust: nightly
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-5
      - g++-5
compiler:
  - gcc
  - clang
env:
  global:
    - LLVM_VERSION=3.9
    - RUST_BACKTRACE=full
    - RUSTFLAGS="-C target-cpu=native"
before_script:
  - if [ "${TRAVIS_OS_NAME}" == "osx" ]; then brew install llvm; fi
  - if [ "${TRAVIS_OS_NAME}" == "linux" ]; then . ./.travis/before_install.sh llvm; fi
  - cd fasthash
script:
  - cargo build --verbose $FEATURES
  - cargo test --verbose $FEATURES
cache:
  cargo: true
  directories:
    - $HOME/.cargo
