sudo: false
language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
  include:
    - os: linux
      env: LLVM_VERSION=3.9
    - os: osx
      env: LLVM_VERSION=devtools
os:
  - linux
  - osx
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-5
compiler:
  - gcc
  - clang
env:
  global:
    - RUST_BACKTRACE=1
before_script:
  - .travis/before-install.sh
  - cd fasthash
script:
  - cargo test
cache:
  cargo: true
  directories:
    - $HOME/.cargo