sudo: false
language: rust
matrix:
  include:
    - os: osx
    - os: linux
    - rust: stable
    - rust: beta
    - rust: nightly
      env: FEATURES="--no-default-features"
  fast_finish: true
  allow_failures:
    - rust: nightly
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-5
      - g++-5
compiler:
  - gcc
  - clang
env:
  global:
    - RUST_BACKTRACE=1
    - LLVM_VERSION=3.9
before_script:
  - if [ "${TRAVIS_OS_NAME}" == "osx" ]; then brew install llvm; fi
  - if [ "${TRAVIS_OS_NAME}" == "linux" ]; then . ./.travis/before_install.sh llvm; fi
  - cd fasthash
script:
  - cargo build --verbose $FEATURES
  - cargo test --verbose $FEATURES
  - 'if [ $TRAVIS_RUST_VERSION = nightly ]; then cargo bench --no-run; fi'
cache:
  cargo: true
  directories:
    - $HOME/.cargo