sudo: false
language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
os:
  - linux
  - osx
addons:
  apt:
    sources: &apt_sources
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise
      - llvm-toolchain-precise-3.9
    packages:
      - gcc-5
      - g++-5
      - llvm-3.9-dev
      - libclang-3.9-dev
compiler:
  - gcc
  - clang
env:
  global:
    - RUST_BACKTRACE=1
before_script:
  - if [ "${TRAVIS_OS_NAME}" == "osx" ]; then brew install llvm; fi
  - cd fasthash
script:
  - cargo test
cache:
  cargo: true
  directories:
    - $HOME/.cargo