sudo: false
language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
os:
  - linux
  - osx
addons:
  apt:
    packages:
      - llvm-3.6-dev
      - libclang-3.6-dev
compiler:
  - gcc
  - clang
env:
  global:
    - RUST_BACKTRACE=1
before_script:
  - if [ "${TRAVIS_OS_NAME}" == "osx" ]; then brew install llvm; fi
  - cd fasthash
script:
  - cargo test
cache:
  cargo: true
  directories:
    - $HOME/.cargo