sudo: false
language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  include:
    - os: osx
      addons:
        homebrew:
          packages:
            - llvm
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-6
            - g++-6
      env:
        global:
          - CC=gcc-6
          - CXX=g++-6
          - CFLAGS=-lgcc
  allow_failures:
    - rust: nightly
compiler:
  - gcc
  - clang
env:
  global:
    - LLVM_VERSION=6.0
    - RUST_BACKTRACE=full
    - RUSTFLAGS="-C target-cpu=native"
before_script:
  - if [ "${TRAVIS_OS_NAME}" == "linux" ]; then . ./.travis/before_install.sh llvm; fi
  - cd fasthash
script:
  - cargo build -vvv $FEATURES
  - cargo test -vvv $FEATURES
cache:
  cargo: true
  directories:
    - $HOME/.cargo
