[package]
name = "fasthash"
version = "0.2.3"
authors = ["Flier Lu <flier.lu@gmail.com>"]
description = "A suite of non-cryptographic hash functions for Rust."
homepage = "https://github.com/flier/rust-fasthash"
repository = "https://github.com/flier/rust-fasthash.git"
documentation = "https://flier.github.io/rust-fasthash/"
keywords = ["hash", "hashing"]
license = "Apache-2.0"
build = "build.rs"

[features]
default = ["i128", "sse42"]
doc = []
i128 = []
sse42 = ["fasthash-sys/sse42"]
bindgen = ["fasthash-sys/bindgen"]

[dependencies]
extprim = "1.1"
rand = "^0.3"
xoroshiro128 = "0.2"
seahash = "3.0"
fasthash-sys = { version = "0.2.3", path = "../fasthash-sys" }
clippy = { version = "0.*", optional = true }

[dev-dependencies]
fnv = "1.0"