[package]
name = "fasthash"
version = "0.3.2"
authors = ["Flier Lu <flier.lu@gmail.com>"]
description = "A suite of non-cryptographic hash functions for Rust."
homepage = "https://github.com/flier/rust-fasthash"
repository = "https://github.com/flier/rust-fasthash.git"
documentation = "https://flier.github.io/rust-fasthash/"
keywords = ["hash", "hashing"]
license = "Apache-2.0"
build = "build.rs"

[features]
default = ["sse42", "aes", "avx", "avx2", "doc"]
doc = []
sse42 = ["fasthash-sys/sse42"]
aes = ["fasthash-sys/aes"]
avx = ["fasthash-sys/avx"]
avx2 = ["fasthash-sys/avx2"]
gen = ["fasthash-sys/gen"]

[dependencies]
xoroshiro128 = "0.3"
seahash = "3.0"
fasthash-sys = { version = "0.3.2", path = "../fasthash-sys" }
clippy = { version = "0.*", optional = true }

[dev-dependencies]
fnv = "1.0"
rand = "0.5"
