[package]
name = "fasthash-sys"
version = "0.3.0"
authors = ["Flier Lu <flier.lu@gmail.com>"]
description = "A suite of non-cryptographic hash functions for Rust."
homepage = "https://github.com/flier/rust-fasthash"
repository = "https://github.com/flier/rust-fasthash.git"
keywords = ["hash", "hashing"]
license = "Apache-2.0"
build = "build.rs"
links = "fasthash"

[features]
default = ["sse42", "aes", "avx", "avx2"]
sse42 = []
aes = []
avx = ["aes"]
avx2 = ["aes"]
gen = ["bindgen"]

[dependencies]

[build-dependencies]
gcc = "0.3"
bindgen = { version="0.37", optional=true }
