[package]
name = "fasthash-sys"
version = "0.1.0"
authors = ["Flier Lu <flier.lu@gmail.com>"]
build = "build.rs"

[dependencies]

[build-dependencies]
gcc = "0.3"

[build-dependencies.libbindgen]
git = "https://github.com/servo/rust-bindgen"
features = ["llvm_stable"]