[package]
name = "fasthash-sys"
version = "0.2.2"
authors = ["Flier Lu <flier.lu@gmail.com>"]
description = "A suite of non-cryptographic hash functions for Rust."
homepage = "https://github.com/flier/rust-fasthash"
repository = "https://github.com/flier/rust-fasthash.git"
keywords = ["hash", "hashing"]
license = "Apache-2.0"
build = "build.rs"

[features]
default = ["sse42"]
sse42 = []

[dependencies]

[build-dependencies]
gcc = "0.3"
libbindgen = "0.1"
