[package]
name = "fasthash-sys"
version = "0.3.2"
authors = ["Flier Lu <flier.lu@gmail.com>"]
description = "A suite of non-cryptographic hash functions for Rust."
homepage = "https://github.com/flier/rust-fasthash"
repository = "https://github.com/flier/rust-fasthash.git"
keywords = ["hash", "hashing"]
license = "Apache-2.0"
build = "build.rs"
edition = "2018"

[features]
default = ["sse42", "aes", "avx", "avx2"]
sse42 = []
aes = []
avx = ["aes"]
avx2 = ["aes"]
gen = ["bindgen"]

[dependencies]
cfg-if = "0.1"

[build-dependencies]
cc = "1.0"
bindgen = { version="0.51", optional=true }
